version: "3.7"

services:
  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - "5000:80"
    networks:
      - frontend
    depends_on: 
      - redis

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - "5001:80"
    networks:
      - backend
    depends_on: 
      - db

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend
    
  redis:
    image: redis:alpine
    networks:
      - frontend
    ports:
      - "6379"

  db:
    image: postgres:11
    networks:
      - backend
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"




networks:
  frontend:
  backend:

volumes:
  db-data: