FROM ubuntu

RUN apt-get update
RUN apt-get install -y wget httpd
#RUN wget https://gist.github.com/ttwthomas/bcfc524e0328343c6e70d0ac93f4ef3e/archive/a7b8c232554c58dddb06dd7a06025a45f92b0e66.zip

#COPY monFichierDeConf /etc/fichier.conf 
ENTRYPOINT ["/bin/bash"]